name: Master

on: 
   push:
     branches : 
       - master
   pull_request:
     branches : 
       - master

jobs:
  MacOS:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: use Setup-Scheme
      uses: guenchi/setup-scheme@master
      with:
        implementation: chez
           
    - name: install raven
      run: |
           cd /usr/local/bin
           cp chez scheme
           curl -L http://ravensc.com/install | scheme
      
    
